fp32_matmul_precision: "high" # or highest, medium
dynamo_cache_size_limit: 0
compile: true
precision: "bf16-mixed" # https://lightning.ai/docs/pytorch/stable/common/trainer.html#precision
sdpa: ["cudnn"]
