fp32_matmul_precision: "highest" # or high, medium
dynamo_cache_size_limit: 0
compile: true
precision: "32" # https://lightning.ai/docs/pytorch/stable/common/trainer.html#precision
sdpa: ["cudnn", "efficient", "flash", "math"]
