#######################################################
# This file belongs to the core repository.
# If your project repository is a fork of core,
# you are suggested to keep this file untouched in your project.
# This helps avoid merge conflicts when syncing from core.
#######################################################

optimizer: AdamW
peak_lr: 1e-4
end_lr_factor: 0.1
warmup_percent: 10
decay_percent: 100
gnorm_clip: 1.0
weight_decay: 1e-4
