ff: True
_target_: src.models.operator_lit_module.OperatorLitModule

model_dim: 128
f_input_dim: 2
g_input_dim: 1
g_output_dim: 1
dropout: 0.1

preprocessor:
  input_dim: 6
  n_layers: 2
  n_heads: 4
  model_dim: ${model.model_dim}
  widening_factor: 4

encoder:
  n_layers: 6
  n_heads: 4
  model_dim: ${model.model_dim}
  widening_factor: 4
  dropout: ${model.dropout}
  max_seq_len: 4000

decoder:
  n_layers: 4
  n_heads: 4
  model_dim: ${model.model_dim}
  widening_factor: 4
  dropout: ${model.dropout}
  max_seq_len: 4000

compile: true
