_target_: src.models.vicon.Vicon

patch_resolution: 16
patch_num_in: 8
patch_num_out: 8
demo_num: ${data.demo_num} 
short_num_min: 1
dim_channel: 3
dim_token: 256   

transformer:
  _target_: src.models.transformer.TransformerEncoder
  layer:
    _target_: src.models.transformer.TransformerEncoderLayer
    d_model: 256
    nhead: 8
    dim_feedforward: 1024
    mha: "built-in"
  num_layers: 6

compile: true             

