# @package _global_

# Optimization parameters
opt:
  peak_lr: 0.001        # Peak learning rate
  weight_decay: 0.01    # Weight decay for AdamW optimizer
  warmup_percent: 10    # Percentage of warmup steps
  decay_percent: 90     # Percentage of decay steps
  gnorm_clip: 1.0       # Gradient clipping value
  end_lr: 0             # Final learning rate 