print_data:
  _target_: src.callbacks.PrintData
  dirpath: ${paths.output_dir}/data
  print_lv_local: 2
  print_lv_log: 1
  train_max_batches_local: 40
  train_max_batches_log: 20
  valid_max_batches_local: 10
  valid_max_batches_log: 5
  test_max_batches_local: 10
  test_max_batches_log: 5
