# @package _global_

# Path configuration
paths:
  # Output directory, dynamically created by hydra
  output_dir: ${hydra:runtime.output_dir}
  
  # Working directory
  work_dir: ${hydra:runtime.cwd}
  
  # Data directory
  data_dir: ${paths.work_dir}/data
  
  # Log directory
  log_dir: ${paths.work_dir}/logs 