# @package _global_

# Logging configuration
logger:
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
    save_dir: "${paths.log_dir}"
    name: "csv_logs"
    version: ${run_name}_${now:%Y-%m-%d_%H-%M-%S}
    prefix: "" 